### ISSUE TITLE
terminus project:clu failing on GitLab

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-clu-plugin#3]
`terminus project:clu` fails on GitLab ([example job log](https://gitlab.com/ataylorme/example-wordpress-composer-ci-refactor-gitlab-test/-/jobs/332524709)) with the error:

```
Fatal error: Uncaught Error: Class '\Pantheon\TerminusClu\ServiceProviders\RepositoryProviders\GitLab\GitLabProvider' not found in /usr/local/share/terminus-plugins/terminus-clu-plugin/src/ServiceProviders/RepositoryProviders/CluGitTrait.php on line 20
```

The class exists so I'm not sure where the issues is.

The same command passes locally both with the plugin installed and with the `quay.io/pantheon-public/build-tools-ci:6.x` image running in Docker.

Jobs on BitBucket and GitLab pass.

@aaronbauman any ideas?

**Comment by aaronbauman** [comment]
I cut a 1.0.1 release that should fix this.
This should get picked up on the next scheduled job in gitlab

**Comment by ataylorme** [comment]
I'm rebuilding the `pantheon-systems/docker-build-tools-ci` `6.x` image with `1.0.1` and will test on GitLab once the image is built.

**Comment by ataylorme** [comment]
@aaronbauman my [GitLab test job passed](https://gitlab.com/ataylorme/example-wordpress-composer-ci-refactor-gitlab-test/-/jobs/333256292).

Thanks for the help!
