### ISSUE TITLE
Failures running composer update not exposed

### ISSUE THREAD

**Issue by davereid-pfg** [pantheon-systems/terminus-clu-plugin#8]
We had our composer updater job on CircleCI just stop working. Turns out we had a patch applied to a drupal module that was also being updated to a version where the patch was already included. So composer update failed normally, but when the command is run via terminus project:clu, this error is not exposed:

```
  /**
   * Runs `composer update`.
   */
  protected function runComposerUpdate() {
    $args = getenv('CLU_COMPOSER_UPDATE_ARGS') ?: '--no-progress --no-dev --no-interaction';
    return $this->exec("composer update --working-dir={$this->working_dir} $args 2>&1 | tee {$this->working_dir}/vendor/update.log");
  }
```

Our CircleCI job command output:
```
[notice] Running composer update --working-dir=/tmp/local-siteNDIySc --no-interaction --no-progress 2>&1 | tee /tmp/local-siteNDIySc/vendor/update.log
 [notice] Running git -C /tmp/local-siteNDIySc status -s composer.lock
 [notice] No changes detected to composer.lock
CircleCI received exit code 0
```

What running composer update locally resulted in:
```
  - Installing drupal/config_split (1.5.0): Loading from cache
  - Applying patches for drupal/config_split
    https://www.drupal.org/files/issues/2019-08-27/3077437-config-split-database-config-readonly-whitelist.patch (Support database split gray/blacklisted configs as config_readonly whitelist patterns)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2019-08-27/3077437-config-split-database-config-readonly-whitelist.patch

                                                                                                                                                          
  [Exception]                                                                                                                                             
  Cannot apply patch Support database split gray/blacklisted configs as config_readonly whitelist patterns (https://www.drupal.org/files/issues/2019-08-  
  27/3077437-config-split-database-config-readonly-whitelist.patch)!        
```

It looks like composer-lock-updater fixed this in https://github.com/danielbachhuber/composer-lock-updater/pull/41 by adding `set -o pipefail &&` before the `composer update` command.

**Comment by aaronbauman** [comment]
Uh oh, I'm running into an error with this version:

``` [notice] Running set -o pipefail && composer update --working-dir=/tmp/local-site6O4qf9 --no-progress --no-dev --no-interaction 2>&1 | tee /tmp/local-site6O4qf9/vendor/update.log
sh: 1: set: Illegal option -o pipefail
 [error]  Command `set -o pipefail && composer update --working-dir=/tmp/local-site6O4qf9 --no-progress --no-dev --no-interaction 2>&1 | tee /tmp/local-site6O4qf9/vendor/update.log` failed with exit code 2 ```

**Comment by aaronbauman** [comment]
I can't recreate this error locally, nor via circle ssh, so I've really no idea what is going on

**Comment by aaronbauman** [comment]
yeah, ok, so Symfony (and thereby Terminus) defaults to using /bin/sh, but `set -o pipefail` is for bash.
it works fine in the main clu project, because that's probably run through bash, not Symfony

perhaps we need to elevate this command into two parts, rather than piping to `tee` and supressing the output

**Comment by sagannotcarl** [comment]
I'm running into the same issue with the same `sh: 1: set: Illegal option -o pipefail` error.

I posted my error here https://github.com/pantheon-systems/docker-build-tools-ci/issues/64 but if you're having it too then this seems like the more likely source.
